name: Stale
on:
  schedule:
    - cron: "0 10 * * 1"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 90
          days-before-close: 30
          stale-issue-message: "Esta issue está inativa há 90 dias"
          stale-pr-message: "Este PR está inativo há 90 dias"
